openapi: 3.0.0
info:
  title: krisenheld:in-API
  description: API of the krisenheld:in Plattform.
  version: 1.0.1
servers:
- url: https://virtserver.swaggerhub.com/krisenheldin/1.0.1
  description: SwaggerHub API Auto Mocking
paths:
  /users:
    get:
      summary: Returns a list of users.
      operationId: users_get
      responses:
        "200":
          description: A JSON array of employers
        "401":
          $ref: '#/components/responses/UnauthorizedError'
        "404":
          description: Throw 404 if resource was not found
      x-openapi-router-controller: api.controllers.default_controller
    post:
      summary: Creates a new user
      operationId: users_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/user'
        required: true
      responses:
        "201":
          description: Created
        "401":
          $ref: '#/components/responses/UnauthorizedError'
      x-openapi-router-controller: api.controllers.default_controller
  /users/{userId}:
    get:
      summary: Returns a users by ID.
      operationId: users_user_id_get
      parameters:
        - name: userId
          in: path
          description: The ID of the user to return.
          required: true
          style: simple
          explode: false
          schema:
            minimum: 1
            type: integer
      responses:
        "200":
          description: A JSON array of employers
        "401":
          $ref: '#/components/responses/UnauthorizedError'
        "404":
          description: Throw 404 if resource was not found
      x-openapi-router-controller: api.controllers.default_controller
  /employers:
    get:
      summary: Returns a list of employers.
      operationId: employers_get
      responses:
        "200":
          description: A JSON array of employers
        "401":
          $ref: '#/components/responses/UnauthorizedError'
        "404":
          description: Throw 404 if resource was not found
      x-openapi-router-controller: api.controllers.default_controller
    post:
      summary: Creates a new employer
      operationId: employers_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/employer'
        required: true
      responses:
        "201":
          description: Created
        "401":
          $ref: '#/components/responses/UnauthorizedError'
      x-openapi-router-controller: api.controllers.default_controller
  /employers/{employerId}:
    get:
      summary: Returns an employer by ID.
      operationId: employers_employer_id_get
      parameters:
      - name: employerId
        in: path
        description: The ID of the employer to return.
        required: true
        style: simple
        explode: false
        schema:
          minimum: 1
          type: integer
      responses:
        "200":
          description: An employer object.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/employer'
        "401":
          $ref: '#/components/responses/UnauthorizedError'
        "404":
          description: Throw 404 if resource was not found
      x-openapi-router-controller: api.controllers.default_controller
    put:
      summary: Update changes to employer
      operationId: employers_employer_id_put
      parameters:
      - name: employerId
        in: path
        description: The ID of the employer to return.
        required: true
        style: simple
        explode: false
        schema:
          minimum: 1
          type: integer
      responses:
        "200":
          description: An employer object.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/employer'
        "401":
          $ref: '#/components/responses/UnauthorizedError'
        "404":
          description: Throw 404 if resource was not found
      x-openapi-router-controller: api.controllers.default_controller
    delete:
      summary: deletes an employer profile. Admin only
      operationId: employers_employer_id_delete
      parameters:
      - name: employerId
        in: path
        description: The ID of the employer to return.
        required: true
        style: simple
        explode: false
        schema:
          minimum: 1
          type: integer
      responses:
        "200":
          description: employer successfully deleted
        "401":
          $ref: '#/components/responses/UnauthorizedError'
        "404":
          description: Throw 404 if resource was not found
        default:
          description: Something went wrong
      x-openapi-router-controller: api.controllers.default_controller
  /employees:
    get:
      summary: Returns a list of employees.
      operationId: employees_get
      responses:
        "200":
          description: A JSON array of employees
      x-openapi-router-controller: api.controllers.default_controller
    post:
      summary: Creates a new employee
      operationId: employees_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/employer'
        required: true
      responses:
        "201":
          description: Created
      x-openapi-router-controller: api.controllers.default_controller
  /employees/{employeeId}:
    get:
      summary: Returns an employee by ID.
      operationId: employees_employee_id_get
      parameters:
      - name: employeeId
        in: path
        description: The ID of the employee to return.
        required: true
        style: simple
        explode: false
        schema:
          minimum: 1
          type: integer
      responses:
        "200":
          description: An employer object.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/employee'
        "401":
          $ref: '#/components/responses/UnauthorizedError'
        "404":
          description: Throw 404 if resource was not found
      x-openapi-router-controller: api.controllers.default_controller
    put:
      summary: Update changes to employer
      operationId: employees_employee_id_put
      parameters:
      - name: employeeId
        in: path
        description: The ID of the employee to return.
        required: true
        style: simple
        explode: false
        schema:
          minimum: 1
          type: integer
      responses:
        "200":
          description: An employee object.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/employee'
        "401":
          $ref: '#/components/responses/UnauthorizedError'
        "404":
          description: Throw 404 if resource was not found
      x-openapi-router-controller: api.controllers.default_controller
    delete:
      summary: deletes an employee profile. Admin only
      operationId: employees_employee_id_delete
      parameters:
      - name: employeeId
        in: path
        description: The ID of the employee to return.
        required: true
        style: simple
        explode: false
        schema:
          minimum: 1
          type: integer
      responses:
        "200":
          description: employer successfully deleted
        "401":
          $ref: '#/components/responses/UnauthorizedError'
        "404":
          description: Throw 404 if resource was not found
        default:
          description: Something went wrong
      x-openapi-router-controller: api.controllers.default_controller
  /jobs:
    get:
      summary: Returns a list of available jobs.
      operationId: jobs_get
      responses:
        "200":
          description: A JSON array of jobs
      x-openapi-router-controller: api.controllers.default_controller
    post:
      summary: Creates a new job
      operationId: jobs_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/job'
        required: true
      responses:
        "201":
          description: Created
      x-openapi-router-controller: api.controllers.default_controller
  /jobs/{jobId}:
    get:
      summary: Returns a job.
      operationId: jobs_job_id_get
      parameters:
      - name: jobId
        in: path
        description: The ID of the job to return.
        required: true
        style: simple
        explode: false
        schema:
          minimum: 1
          type: integer
      responses:
        "200":
          description: A job object.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/job'
        "401":
          $ref: '#/components/responses/UnauthorizedError'
        "404":
          description: Throw 404 if resource was not found
      x-openapi-router-controller: api.controllers.default_controller
    put:
      summary: Update changes to job
      operationId: jobs_job_id_put
      parameters:
      - name: jobId
        in: path
        description: The ID of the job to return.
        required: true
        style: simple
        explode: false
        schema:
          minimum: 1
          type: integer
      responses:
        "200":
          description: A job object.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/job'
        "401":
          $ref: '#/components/responses/UnauthorizedError'
        "404":
          description: Throw 404 if resource was not found
      x-openapi-router-controller: api.controllers.default_controller
    delete:
      summary: deletes a job
      operationId: jobs_job_id_delete
      parameters:
      - name: jobId
        in: path
        description: The ID of the job to return.
        required: true
        style: simple
        explode: false
        schema:
          minimum: 1
          type: integer
      responses:
        "200":
          description: job successfully deleted
        "401":
          $ref: '#/components/responses/UnauthorizedError'
        "404":
          description: Throw 404 if resource was not found
        default:
          description: Something went wrong
      x-openapi-router-controller: api.controllers.default_controller
  /jobs/{jobId}/pictures:
    get:
      summary: Returns a list of pictures for the specified job.
      operationId: jobs_job_id_pictures_get
      parameters:
      - name: jobId
        in: path
        description: The ID of the job
        required: true
        style: simple
        explode: false
        schema:
          minimum: 1
          type: string
      responses:
        "200":
          description: A list of pictures for the specified job
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/picture'
                x-content-type: application/json
        "401":
          $ref: '#/components/responses/UnauthorizedError'
        "404":
          description: Throw 404 if resource was not found
      x-openapi-router-controller: api.controllers.default_controller
    post:
      summary: Creates a new job picture
      operationId: jobs_job_id_pictures_post
      parameters:
        - name: jobId
          in: path
          description: The ID of the job
          required: true
          style: simple
          explode: false
          schema:
            minimum: 1
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/picture'
        required: true
      responses:
        "201":
          description: Created
      x-openapi-router-controller: api.controllers.default_controller
  /jobs/{jobId}/pictures/{pictureId}:
    get:
      summary: gets a picture
      operationId: jobs_job_id_pictures_picture_id_get
      parameters:
      - name: jobId
        in: path
        description: The ID of the job to return.
        required: true
        style: simple
        explode: false
        schema:
          minimum: 1
          type: integer
      - name: pictureId
        in: path
        description: The ID of the picture to show.
        required: true
        style: simple
        explode: false
        schema:
          minimum: 1
          type: integer
      responses:
        "200":
          description: job successfully deleted
        "401":
          $ref: '#/components/responses/UnauthorizedError'
        "404":
          description: Throw 404 if resource was not found
        default:
          description: Something went wrong
      x-openapi-router-controller: api.controllers.default_controller
    delete:
      summary: deletes a picture
      operationId: jobs_job_id_pictures_picture_id_delete
      parameters:
      - name: jobId
        in: path
        description: The ID of the job to return.
        required: true
        style: simple
        explode: false
        schema:
          minimum: 1
          type: integer
      - name: pictureId
        in: path
        description: The ID of the picture to delete.
        required: true
        style: simple
        explode: false
        schema:
          minimum: 1
          type: integer
      responses:
        "200":
          description: job successfully deleted
        "401":
          $ref: '#/components/responses/UnauthorizedError'
        "404":
          description: Throw 404 if resource was not found
        default:
          description: Something went wrong
      x-openapi-router-controller: api.controllers.default_controller
  /applications:
    post:
      summary: Creates a new application
      operationId: applications_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/jobApplication'
        required: true
      responses:
        "201":
          description: Created
      x-openapi-router-controller: api.controllers.default_controller
  /applications/{applicationId}:
    get:
      summary: Returns an application.
      operationId: applications_application_id_get
      parameters:
      - name: applicationId
        in: path
        description: The ID of the application to return.
        required: true
        style: simple
        explode: false
        schema:
          minimum: 1
          type: integer
      responses:
        "200":
          description: An application object.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/jobApplication'
        "401":
          $ref: '#/components/responses/UnauthorizedError'
        "404":
          description: Throw 404 if resource was not found
      x-openapi-router-controller: api.controllers.default_controller
    put:
      summary: Update changes to application
      operationId: applications_application_id_put
      parameters:
      - name: applicationId
        in: path
        description: The ID of the application to return.
        required: true
        style: simple
        explode: false
        schema:
          minimum: 1
          type: integer
      responses:
        "200":
          description: An application object.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/jobApplication'
        "401":
          $ref: '#/components/responses/UnauthorizedError'
        "404":
          description: Throw 404 if resource was not found
      x-openapi-router-controller: api.controllers.default_controller
    delete:
      summary: deletes an application
      operationId: applications_application_id_delete
      parameters:
      - name: applicationId
        in: path
        description: The ID of the application to return.
        required: true
        style: simple
        explode: false
        schema:
          minimum: 1
          type: integer
      responses:
        "200":
          description: application successfully deleted
        "401":
          $ref: '#/components/responses/UnauthorizedError'
        "404":
          description: Throw 404 if resource was not found
        default:
          description: Something went wrong
      x-openapi-router-controller: api.controllers.default_controller
  /jobs_near:
    get:
      summary: Returns a list of jobs in the specified search area.
      operationId: jobs_near_get
      parameters:
      - name: lat
        in: query
        required: false
        style: form
        explode: true
        schema:
          type: number
          description: Latitude of search center
      - name: lng
        in: query
        required: false
        style: form
        explode: true
        schema:
          type: number
          description: Longitude of search center
      - name: radius
        in: query
        required: false
        style: form
        explode: true
        schema:
          type: number
          description: Radius of search
      - name: limit
        in: query
        required: false
        style: form
        explode: true
        schema:
          type: integer
          description: Maximum number of hits to be returned
      responses:
        "200":
          description: A list of jobs in the search area. Ordered by distance
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/job'
                x-content-type: application/json
        "401":
          $ref: '#/components/responses/UnauthorizedError'
        "404":
          description: Throw 404 if resource was not found
        default:
          description: Something went wrong
      x-openapi-router-controller: api.controllers.default_controller
  /contracts/{contractId}:
    get:
      summary: Returns the specified contract of jobs.
      operationId: contracts_contract_id_get
      parameters:
      - name: contractId
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          description: Id of the contract to show
      responses:
        "200":
          description: The specified contract
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/contract'
                x-content-type: application/json
        "401":
          $ref: '#/components/responses/UnauthorizedError'
        "404":
          description: Throw 404 if resource was not found
        default:
          description: Something went wrong
      x-openapi-router-controller: api.controllers.default_controller
  /login:
    post:
      summary: Userlogin, returns the users jwttoken for authentication. WARNING potentially insecure, revision required
      operationId: login_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/loginCredentials'
        required: true
      responses:
        "200":
          description: Created
          content:
            application/json:
              schema:
                type: object
                description: Bearer token containg userclaims. Needs revision!
        "401":
          $ref: '#/components/responses/UnauthorizedError'
        default:
          description: Something went wrong
      x-openapi-router-controller: api.controllers.default_controller
components:
  responses:
    UnauthorizedError:
      description: Access token is missing or invalid
  # securitySchemes:
  #   jwtAuth:
  #     type: http
  #     scheme: bearer
  #     bearerFormat: JWT
  #     x-bearerInfoFunc: app.decode_token # connexion rule!
  schemas:
    employer:
      type: object
      properties:
        id:
          type: integer
          example: 1234
          readOnly: true # only visible in GET - not available in POST/PUT
        userId:
          type: integer
          example: 12
        defaultPictureId:
          type: integer
          example: 23
        companyName:
          type: string
          example: MaxiMarkt
        industry:
          type: string
          example: Lebensmittelhandel
        description:
          type: string
          example: Wir lieben Lebensmittel
        firstName:
          type: string
          example: Holger
        lastName:
          type: string
          example: Müller
        street:
          type: string
          example: Feldstraße
        houseNumber:
          type: string
          example: 135a
        postalCode:
          type: string
          example: "02321"
        city:
          type: string
          example: Schöndorf
        state:
          type: string
          example: Nordrhein-Westfalen
      example:
        companyName: MaxiMarkt
        industry: Lebensmittelhandel
        description: Wir lieben Lebensmittel
        firstName: Holger
        lastName: Müller
        city: Schöndorf
        street: Feldstraße
        postalCode: "02321"
        houseNumber: 135a
        defaultPictureId: 23
        id: 1234
        userId: 12
        state: Nordrhein-Westfalen
    employee:
      type: object
      properties:
        id:
          type: integer
          example: 456
          readOnly: true # only visible in GET - not available in POST/PUT
        userId:
          type: integer
          example: 13
        firstName:
          type: string
          example: Hans
        lastName:
          type: string
          example: Meier
        description:
          type: string
          example: Ich bin hoch motiviert!
        street:
          type: string
          example: Feldstraße
        houseNumber:
          type: string
          example: 135a
        postalCode:
          type: string
          example: "02321"
        city:
          type: string
          example: Schöndorf
        state:
          type: string
          example: Nordrhein-Westfalen
      example:
        firstName: Hans
        lastName: Meier
        city: Schöndorf
        street: Feldstraße
        postalCode: "02321"
        houseNumber: 135a
        id: 456
        userId: 13
        state: Nordrhein-Westfalen
        description: Ich bin hoch motiviert!
    job:
      type: object
      properties:
        id:
          type: integer
          example: 126464
          readOnly: true # only visible in GET - not available in POST/PUT
        employerId:
          type: integer
          example: 1234
        defaultImagePictureId:
          type: integer
          example: 23
        description:
          type: string
          example: Aushilfe bei der Belieferung von Lebensmittelhandel
        salaryHourly:
          type: number
          example: 9.75
        workHoursPerDay:
          type: number
          example: 8
        workDaysPerWeek:
          type: number
          example: 5
        accommodationAvailable:
          type: boolean
          example: true
        acommodationCostPerDay:
          type: number
          example: 9.5
        withMeals:
          type: boolean
          example: true
        mealCostPerDay:
          type: number
          example: 5.5
        spokenLanguages:
          type: string
          example: deutsch, english, polish
        location:
          $ref: '#/components/schemas/job_location'
        locationDescription:
          type: string
          example: nahe Bad Wünnenberg
        startDate:
          type: string
          format: date
          example: 01.05.2020
        endDate:
          type: string
          format: date
          example: 30.05.2020
        specialRequirements:
          type: string
          example: führerschein Kl. B
        contingent:
          type: number
          example: 100
        isActive:
          type: boolean
          example: true
        visibleFrom:
          type: string
          format: date
          example: 01.05.2020
        visibleTo:
          type: string
          format: date
          example: 30.05.2020
      example:
        acommodationCostPerDay: 9.5
        endDate: 30.05.2020
        locationDescription: nahe Bad Wünnenberg
        accommodationAvailable: true
        withMeals: true
        description: Aushilfe bei der Belieferung von Lebensmittelhandel
        contingent: 100
        isActive: true
        defaultImagePictureId: 23
        workHoursPerDay: 8
        employerId: 1234
        workDaysPerWeek: 5
        spokenLanguages: deutsch, english, polish
        location:
          lng: 8.666
          lat: 51.55133
        visibleTo: 30.05.2020
        id: 126464
        salaryHourly: 9.75
        mealCostPerDay: 5.5
        visibleFrom: 01.05.2020
        startDate: 01.05.2020
        specialRequirements: führerschein Kl. B
    jobApplication:
      type: object
      properties:
        id:
          type: integer
          example: 1234
          readOnly: true # only visible in GET - not available in POST/PUT
        jobId:
          type: integer
          example: 123423
        employeeId:
          type: integer
          example: 2342
        employeeStatus:
          type: string
          example: available
        employerStatus:
          type: string
          example: available
      example:
        jobId: 123423
        employerStatus: available
        employeeId: 2342
        id: 1234
        employeeStatus: available
    contract:
      type: object
      properties:
        id:
          type: integer
          example: 
          readOnly: true # only visible in GET - not available in POST/PUT
        jobApplicationId:
          type: integer
          example: 123455
        employerSigned:
          type: string
          format: date
          example: 12.5.2020
        employeeSigned:
          type: string
          format: date
          example: 12.5.2020
      example:
        employerSigned: 12.5.2020
        jobApplicationId: 123455
        id: 121
        employeeSigned: 12.5.2020
    address:
      type: object
      properties:
        street:
          type: string
          example: Feldstraße
        houseNumber:
          type: string
          example: 75a
        postalCode:
          type: string
          example: "64544"
        state:
          type: string
          example: Nordrhein-Westfalen
    document:
      type: object
      properties:
        documentType:
          type: string
          example: media/pdf
        path:
          type: string
          example: media.krisenheldin.de/employees_documents/164sc234d654.pdf
    picture:
      type: object
      properties:
        documentType:
          type: string
          example: image/jpeg
        path:
          type: string
          example: media.krisenheldin.de/employer_pictures/qwre132410.pdf
      example:
        path: media.krisenheldin.de/employer_pictures/qwre132410.pdf
        documentType: image/jpeg
    loginCredentials:
      type: object
      properties:
        email:
          type: string
          example: hansel@xx.de
        password:
          type: string
          example: secure
    job_location:
      type: object
      properties:
        lat:
          type: number
          example: 51.55133
        lng:
          type: number
          example: 8.666
      example:
        lng: 8.666
        lat: 51.55133
    user:
      type: object
      properties:
        id:
          type: integer
          example: 1234
          readOnly: true # only visible in GET - not available in POST/PUT
        login:
          type: string
          example: sepp@mail.de
        password:
          type: string
          format: password
          example: xöd09383dff
          writeOnly: true # only passed in POST/PUT - not visible in GET
      example:
        id: 1234
        login: sepp@mail.de
        password: xöd09383dff
  # security globally to all operations
#security:
#  - jwtAuth: []         # use the same name as above
  
